services:
  postgres:
    image: postgres:16-alpine
    container_name: saldofy-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: saldofy
      POSTGRES_PASSWORD: saldofy123
      POSTGRES_DB: saldofy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: